Repository buildbot/buildbot, pull requests merged in 2019-01, with the labels that each got.

#4543 Fix buildbot sendchange on Python 3
  master/buildbot/clients/sendchange.py
  master/buildbot/newsfragments/sendchange-py3.bugfix
  master/buildbot/test/unit/test_clients_sendchange.py
Labels: py3

#4532 Remove Python 3.4 support from the buildbot master
  .bbtravis.yml
  master/buildbot/newsfragments/python-3.4.removal
  master/docs/manual/installation/requirements.rst
  master/setup.py
Labels: Do Not Merge

#4542 Allows more UTF-8 characters in builder names, worker names, and step names
  master/buildbot/newsfragments/utf8-identifier.feature
  master/buildbot/test/unit/test_config.py
  master/buildbot/test/unit/test_test_util_validation.py
  master/buildbot/test/unit/test_util_identifiers.py
  master/buildbot/test/util/validation.py
  master/buildbot/util/identifiers.py
  master/docs/developer/database.rst
  master/docs/developer/utils.rst
  master/docs/manual/upgrading/nine-upgrade.rst
Labels: Do Not Merge, bytes

#4536 db: fix foreign key constraints for "nullable" columns
  master/buildbot/db/migrate/versions/052_cascading_set_null.py
  master/buildbot/db/model.py
  master/buildbot/newsfragments/master-db-integrity.bugfix
  master/buildbot/test/unit/test_db_migrate_versions_052_cascading_set_null.py
Labels: Do Not Merge
